import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();
  console.log("session", session);
  console.log("session", !session);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {session && (
            <button className="text-white" onClick={() => signOut()}>
              Sign out
            </button>
          )}
          {!session && (
            <button className="text-white" onClick={() => signIn()}>
              Sign in
            </button>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
